spring:

  datasource:
    username: vike0906
    password: v123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.222.152:9001/vike?characterEncoding=UTF-8
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      validation-timeout: 1000
      idle-timeout: 300000
      maximum-pool-size: 20
      destroy-method: shutdown

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      use_query_cache: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  data:
    mongodb:
      uri: mongodb://stock:123456@106.13.222.152:9003/stockdb

logging:
  config: classpath:logs/dev.xml

system:
  ## session过期时间
  loginTimeOut: 1800

